version: "3"
services:
  api:
    build: ./
    ports:
    - "8083:8080"
    environment:
    - SPRING_PROFILES_ACTIVE=stage
    depends_on:
    - postgres

  postgres:
    image: "postgres:10"
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=contacts
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data:
